name: Build Wallet 2.0 for Android

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  BuildAndroidApp:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        shell: bash
        run: |
          CI_REF=${{ github.ref }}
          IS_RELEASE_BUILD=$(if [ $(cut -d'/' -f2 <<<$CI_REF) = "tags" ]; then printf 'true'; else printf 'false'; fi) # Determines if we're creating a release (tagged) build.
          IS_BETA_BUILD=$(if [ $CI_REF = "refs/heads/staging" ]; then printf 'true'; else printf 'false'; fi) # Determines if we're creating a beta (staging branch) build. 
          IS_RETAIL_BUILD=$(if [ $IS_RELEASE_BUILD = "true" ] || [ $CI_REF = "refs/heads/master" ] || [ $IS_BETA_BUILD = "true" ]; then printf 'true'; else printf 'false'; fi) # Determines if we're creating a non-development build.
          SHA=$(printf '${{ github.sha }}' | cut -c 1-8)
          if [ $CI_REF == "refs/heads/staging" ]; then SUFFIX=beta
          elif [ $CI_REF == "refs/heads/master" ]; then SUFFIX=rc
          elif [ $CI_REF == *"refs/tags/v"* ]; then SUFFIX=${GITHUB_REF##*/}
          else SUFFIX=dev; fi
          [ $CI_REF != *"refs/tags"* ] && SUFFIX+=.$SHA
          echo $CI_REF
          echo "$SUFFIX"
