name: Build Wallet 2.0 for Android

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  BuildAndroidApp:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        shell: bash
        run: |
          SHA=$(printf '${{ github.sha }}' | cut -c 1-8)
          CI_REF=${{ github.ref }}
          IS_RELEASE_BUILD=$(if [ $(cut -d'/' -f2 <<<$CI_REF) = "tags" ] && [ $CI_REF = "refs/heads/master" ]; then printf 'true'; else printf 'false'; fi) # Determines if we're creating a release (tagged on master branch) build.
          IS_BETA_BUILD=$(if [ $CI_REF = "refs/heads/staging" ]; then printf 'true'; else printf 'false'; fi) # Determines if we're creating a beta (staging branch) build.
          IS_RC_BUILD=$(if [ $CI_REF = "refs/heads/master" ]; then printf 'true'; else printf 'false'; fi) # Determines if we're creating a RC (master branch) build.
          IS_RETAIL_BUILD=$(if [ $IS_RELEASE_BUILD = "true" ] || [ $IS_RC_BUILD = "true" ] || [ $IS_BETA_BUILD = "true" ]; then printf 'true'; else printf 'false'; fi) # Determines if we're creating a non-development build.
          if $IS_BETA_BUILD; then SUFFIX=beta
          elif $IS_RC_BUILD; then SUFFIX=rc
          elif $IS_RELEASE_BUILD; then SUFFIX=${GITHUB_REF##*/}
          else SUFFIX=dev; fi
          [ $IS_RELEASE_BUILD != "true" ] && SUFFIX+=.$SHA
          echo "CI_REF=$CI_REF"
          echo "SUFFIX=$SUFFIX"
          echo "IS_RELEASE_BUILD=$IS_RELEASE_BUILD"
          echo "IS_BETA_BUILD=$IS_BETA_BUILD"
          echo "IS_RC_BUILD=$IS_RC_BUILD"
          echo "IS_RETAIL_BUILD=$IS_RETAIL_BUILD"
