name: Build Wallet 2.0 for Android

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  BuildAndroidApp:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables
        shell: bash
        run: |
          CI_SHA_SHORT=$(printf '${{ github.sha }}' | cut -c 1-8)
          if [[ ${{ github.ref }} == "refs/heads/staging" ]]; then SUFFIX=beta
          elif [[ ${{ github.ref }} == "refs/heads/master" ]]; then SUFFIX=rc
          elif [[ ${{ github.ref }} == *"refs/tags"* ]]; then SUFFIX=$CI_REF_NAME
          else SUFFIX=dev; fi
          [[ ${{ github.ref }} != *"refs/tags"* ]] && SUFFIX+=.$CI_SHA_SHORT
          echo ${{ github.ref }}
          echo "$SUFFIX"
